apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
- deployment.yaml
- service.yaml
- ingress.yaml

commonLabels:
  environment: production
  deployment: production

commonAnnotations:
  description: "Production Kubernetes deployment for Order Processor application"
  environment: "production"
  cluster: "aws-eks-order-processor-prod"

images:
- name: order-processor-user-service
  newName: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/order-processor-prod-user-service
  newTag: ${IMAGE_TAG}
- name: order-processor-inventory-service
  newName: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/order-processor-prod-inventory-service
  newTag: ${IMAGE_TAG}
- name: order-processor-order-service
  newName: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/order-processor-prod-order-service
  newTag: ${IMAGE_TAG}
- name: order-processor-auth-service
  newName: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/order-processor-prod-auth-service
  newTag: ${IMAGE_TAG}
- name: order-processor-gateway
  newName: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/order-processor-prod-gateway
  newTag: ${IMAGE_TAG}