apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: order-processor-production
  namespace: order-processor

resources:
- ../base
- service-account.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- secrets.yaml

labels:
  environment: production
  deployment: production

commonAnnotations:
  description: "Production Kubernetes deployment for Order Processor application"
  environment: "production"
  cluster: "aws-eks-order-processor-prod"

images:
- name: docker-user_service
  newName: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/order-processor-user-service
  newTag: latest
- name: docker-inventory_service
  newName: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/order-processor-inventory-service
  newTag: latest
- name: docker-order_service
  newName: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/order-processor-order-service
  newTag: latest
- name: docker-auth_service
  newName: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/order-processor-auth-service
  newTag: latest
- name: docker-frontend-dev
  newName: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/order-processor-frontend
  newTag: latest