apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-processor-sa
  namespace: order-processor
  labels:
    app: order-processor
    component: service-account
    environment: production
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::${AWS_ACCOUNT_ID}:role/order-processor-prod-application-service-role"
    eks.amazonaws.com/sts-regional-endpoints: "true"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: order-processor-role
  namespace: order-processor
  labels:
    app: order-processor
    component: role
    environment: production
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: order-processor-rolebinding
  namespace: order-processor
  labels:
    app: order-processor
    component: rolebinding
    environment: production
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: order-processor-role
subjects:
- kind: ServiceAccount
  name: order-processor-sa
  namespace: order-processor