# File: pytest.ini
# pytest.ini - Test configuration
[tool:pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    -v
    --tb=short
    --strict-markers
    --color=yes
    --durations=10
markers =
    infrastructure: Infrastructure integration tests
    slow: Slow running tests
    aws: Tests that require AWS credentials
    skip_ci: Skip in CI environment

# Test timeout (10 minutes for infrastructure tests)
timeout = 600