server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # FastAPI JSON logs from your services
  - job_name: fastapi-services
    static_configs:
      - targets:
          - localhost
        labels:
          job: fastapi-services
          __path__: /var/log/services/*/logs/*.log

    pipeline_stages:
      # Parse JSON logs
      - json:
          expressions:
            timestamp: timestamp
            level: level
            service: service
            request_id: request_id
            action: action
            message: message
            user: user
            duration_ms: duration_ms

      # Extract labels for filtering
      - labels:
          service:
          level:
          action:
          user:

      # Set timestamp
      - timestamp:
          source: timestamp
          format: RFC3339

  # Docker container logs
  - job_name: docker-containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: container_name
      - source_labels: [__meta_docker_container_log_stream]
        target_label: log_stream

    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            service: service
            message: message
      - labels:
          service:
          level:
