apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: order-processor
  labels:
    app: order-processor
    component: user-service
    environment: local
spec:
  type: NodePort
  selector:
    app: order-processor
    component: user-service
  ports:
  - name: http
    port: 30001
    targetPort: 8000
    nodePort: 30001
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: order-processor
  labels:
    app: order-processor
    component: inventory-service
    environment: local
spec:
  type: NodePort
  selector:
    app: order-processor
    component: inventory-service
  ports:
  - name: http
    port: 30002
    targetPort: 8001
    nodePort: 30002
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: order-processor
  labels:
    app: order-processor
    component: frontend
    environment: local
spec:
  type: NodePort
  selector:
    app: order-processor
    component: frontend
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    nodePort: 30000
    protocol: TCP