version: '3.8'

services:
  order-service:
    build:
      target: development
    volumes:
      - ../../services/order-service/src:/app/src:ro
      - ./config/environment/.env.local:/app/.env
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - FLASK_ENV=development
      - PYTHONDONTWRITEBYTECODE=1
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    ports:
      - "8000:8000"
      - "5678:5678"  # Debug port
    command: ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "--wait-for-client", "src/app.py"]

  postgres:
    ports:
      - "5433:5432"  # Different port to avoid conflicts
    environment:
      POSTGRES_DB: orderdb_dev
      POSTGRES_USER: orderuser_dev
      POSTGRES_PASSWORD: orderpass_dev
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

  redis:
    ports:
      - "6380:6379"  # Different port to avoid conflicts

  localstack:
    ports:
      - "4567:4566"  # Different port to avoid conflicts

volumes:
  postgres_dev_data: