services:
  frontend-dev:
    build:
      context: ../
      dockerfile: docker/frontend/Dockerfile.dev
    container_name: order-processor-frontend-dev
    ports:
      - "3000:3000"
    depends_on:
      - user_service
      - inventory_service
    networks:
      - order-processor-network
    # Development volumes for hot reloading
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true

  user_service:
    build:
      context: ../
      dockerfile: docker/user-service/Dockerfile
    container_name: order-processor-user_service
    ports:
      - "8000:8000"
    environment:
      - ORDERS_TABLE=order-processor-dev-orders
      - INVENTORY_TABLE=order-processor-dev-inventory
      - USERS_TABLE=order-processor-dev-users
      - AWS_REGION=us-west-2
      - JWT_SECRET=your-development-jwt-secret-key-here
      - JWT_ALGORITHM=HS256
      - JWT_EXPIRATION_HOURS=24
      - SERVICE_NAME=user_service
      - SERVICE_PORT=8000
      - ENVIRONMENT=development
      - LOG_LEVEL=INFO
    volumes:
      - ~/.aws:/root/.aws:ro
      # Auto-reload for development
      - ../services:/app/services:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - order-processor-network

  inventory_service:
    build:
      context: ../
      dockerfile: docker/inventory-service/Dockerfile
    container_name: order-processor-inventory_service
    ports:
      - "8001:8001"
    environment:
      - ORDERS_TABLE=order-processor-dev-orders
      - INVENTORY_TABLE=order-processor-dev-inventory
      - USERS_TABLE=order-processor-dev-users
      - AWS_REGION=us-west-2
      - SERVICE_NAME=inventory_service
      - SERVICE_PORT=8001
      - ENVIRONMENT=development
      - LOG_LEVEL=INFO
    volumes:
      - ~/.aws:/root/.aws:ro
      # Auto-reload for development
      - ../services:/app/services:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - order-processor-network

networks:
  order-processor-network:
    name: order-processor-network
    driver: bridge