# docker/pytest.ini
[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -ra -q --strict-markers --tb=short
markers =
    unit: Unit tests (fast)
    integration: Integration tests (slower)
    slow: Slow tests
    skip_ci: Skip in CI environment
env_files =
    .env.test
EOF

# docker/.flake8
cat > docker/.flake8 << 'EOF'
[flake8]
max-line-length = 100
exclude = 
    .git,
    __pycache__,
    .venv,
    venv,
    .pytest_cache,
    .mypy_cache
ignore = 
    E203,  # whitespace before ':'
    W503,  # line break before binary operator
    E501   # line too long (handled by black)
per-file-ignores =
    __init__.py:F401