apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: order-processor-dev
  namespace: order-processor

resources:
- ../base
- ../secrets/deployment_dev.yaml
- service.yaml

images:
- name: order-processor-user_service
  newTag: latest
- name: order-processor-inventory_service
  newTag: latest
- name: order-processor-frontend
  newTag: latest