apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: order-processor-dev
  namespace: order-processor

resources:
- ../base
- deployment.yaml
- service.yaml
- secrets.yaml

commonLabels:
  environment: dev
  deployment: dev

commonAnnotations:
  description: "Dev Kubernetes deployment for Order Processor application"
  environment: "dev"
  cluster: "kind-order-processor"

images:
- name: order-processor-user_service
  newTag: latest
- name: order-processor-inventory_service
  newTag: latest
- name: order-processor-frontend
  newTag: latest