# Dev Environment Values
# Used for Kind cluster deployment

environment: dev
namespace: order-processor

# Service Configuration
services:
  user-service:
    replicas: 1
    port: 8000
    nodePort: 30001
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"

  inventory-service:
    replicas: 1
    port: 8001
    nodePort: 30002
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"

  frontend:
    replicas: 1
    port: 3000
    nodePort: 30000
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"

# Database Configuration
database:
  region: "${AWS_REGION}"
  tables:
    users: "order-processor-dev-users"
    orders: "order-processor-dev-orders"
    inventory: "order-processor-dev-inventory"

# AWS Configuration
aws:
  region: "${AWS_REGION}"
  account_id: "${AWS_ACCOUNT_ID}"
  role_arn: "arn:aws:iam::${AWS_ACCOUNT_ID}:role/order-processor-dev-application-service-role"

# Application Configuration
app:
  jwt_secret: "dev-secret-key"
  environment: "development"

# External URLs (for frontend)
urls:
  api: "http://localhost:30000"
  user_service: "http://localhost:30001"
  inventory_service: "http://localhost:30002"