apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: order-processor

resources:
  - namespace.yaml
  - service-account.yaml
  # Removed: redis.yaml, logging-config.yaml, monitoring.yaml for minimal deployment

commonLabels:
  app.kubernetes.io/name: order-processor
  app.kubernetes.io/part-of: order-processor
  app.kubernetes.io/component: base

commonAnnotations:
  kustomize.config.k8s.io/needs-hash-suffix: "true"