apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: order-processor-base
  namespace: order-processor

resources:
  - namespace.yaml
  - service-account.yaml
  - logging-config.yaml
  - ../secrets/

commonLabels:
  app: order-processor
  environment: base
  version: v1.0.0

commonAnnotations:
  description: "Base configuration for Order Processor application"