# kubernetes/base/redis.yaml
# Redis deployment for local K8s development
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: order-processor
  labels:
    app: order-processor
    component: redis
data:
  redis.conf: |
    # Redis configuration for local development
    maxmemory 128mb
    maxmemory-policy allkeys-lru
    # Persistence for local development
    save 900 1
    save 300 10
    save 60 10000
    # Disable protected mode for local development
    protected-mode no
    # Enable logging
    loglevel notice
    logfile ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: order-processor
  labels:
    app: order-processor
    component: redis
    environment: base
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-processor
      component: redis
  template:
    metadata:
      labels:
        app: order-processor
        component: redis
        environment: base
    spec:
      serviceAccountName: order-processor-sa
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
          name: redis
        command:
          - redis-server
          - /etc/redis/redis.conf
        volumeMounts:
        - name: config
          mountPath: /etc/redis
        - name: data
          mountPath: /data
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 999  # Redis user in alpine image
          allowPrivilegeEscalation: false
      volumes:
      - name: config
        configMap:
          name: redis-config
      - name: data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: order-processor
  labels:
    app: order-processor
    component: redis
    environment: base
spec:
  selector:
    app: order-processor
    component: redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
  type: ClusterIP