apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-processor-sa
  namespace: order-processor
  labels:
    app: order-processor
    component: service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: order-processor-role
  namespace: order-processor
  labels:
    app: order-processor
    component: role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: order-processor-rolebinding
  namespace: order-processor
  labels:
    app: order-processor
    component: rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: order-processor-role
subjects:
- kind: ServiceAccount
  name: order-processor-sa
  namespace: order-processor