# templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-processor-config
  namespace: order-processor
  labels:
    app: order-processor
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
data:
  # AWS Configuration
  AWS_REGION: "{{ .Values.aws.region }}"
  AWS_ACCOUNT_ID: "{{ .Values.aws.accountId }}"
  
  # Database Configuration
  DB_HOST: "{{ .Values.database.host }}"
  DB_PORT: "{{ .Values.database.port }}"
  DB_NAME: "{{ .Values.database.name }}"
  DB_USERNAME: "{{ .Values.database.username }}"
  
  # DynamoDB Tables
  ORDERS_TABLE: "{{ .Values.dynamodb.ordersTable }}"
  INVENTORY_TABLE: "{{ .Values.dynamodb.inventoryTable }}"
  USERS_TABLE: "{{ .Values.dynamodb.usersTable }}"
  
  # SQS Queue URLs
  PAYMENT_QUEUE_URL: "https://sqs.{{ .Values.aws.region }}.amazonaws.com/{{ .Values.aws.accountId }}/{{ .Values.sqs.paymentQueue.name }}"
  NOTIFICATION_QUEUE_URL: "https://sqs.{{ .Values.aws.region }}.amazonaws.com/{{ .Values.aws.accountId }}/{{ .Values.sqs.notificationQueue.name }}"
  
  # SNS Topic ARNs
  ORDER_NOTIFICATIONS_TOPIC_ARN: "arn:aws:sns:{{ .Values.aws.region }}:{{ .Values.aws.accountId }}:{{ .Values.sns.orderNotifications.name }}"
  
  # Lambda Function ARNs
  PAYMENT_PROCESSOR_ARN: "arn:aws:lambda:{{ .Values.aws.region }}:{{ .Values.aws.accountId }}:function:{{ .Values.lambda.paymentProcessor.name }}"
  NOTIFICATION_SERVICE_ARN: "arn:aws:lambda:{{ .Values.aws.region }}:{{ .Values.aws.accountId }}:function:{{ .Values.lambda.notificationService.name }}"
  
  # Application URLs
  ORDER_API_URL: "http://order-api:{{ .Values.orderApi.port }}"
  INVENTORY_SERVICE_URL: "http://inventory-service:{{ .Values.inventoryService.port }}"
  
  {{- if .Values.debug.enabled }}
  # Debug Configuration
  DEBUG: "true"
  LOG_LEVEL: "{{ .Values.debug.logLevel }}"
  {{- end }}