# templates/inventory-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: order-processor
  labels:
    app: inventory-service
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.inventoryService.replicas }}
  selector:
    matchLabels:
      app: inventory-service
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: inventory-service
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: inventory-service-sa
      containers:
      - name: inventory-service
        image: "{{ .Values.aws.accountId }}.dkr.ecr.{{ .Values.aws.region }}.amazonaws.com/{{ .Values.images.inventoryService.repository }}:{{ .Values.images.inventoryService.tag }}"
        ports:
        - containerPort: {{ .Values.inventoryService.port }}
        env:
        # AWS Configuration
        - name: AWS_REGION
          value: "{{ .Values.aws.region }}"
        - name: AWS_ACCOUNT_ID
          value: "{{ .Values.aws.accountId }}"
        
        # Database Configuration
        - name: DB_HOST
          value: "{{ .Values.database.host }}"
        - name: DB_PORT
          value: "{{ .Values.database.port }}"
        - name: DB_NAME
          value: "{{ .Values.database.name }}"
        - name: DB_USERNAME
          value: "{{ .Values.database.username }}"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        
        # DynamoDB Tables
        - name: INVENTORY_TABLE
          value: "{{ .Values.dynamodb.inventoryTable }}"
        - name: ORDERS_TABLE
          value: "{{ .Values.dynamodb.ordersTable }}"
        
        # SQS Queues
        - name: NOTIFICATION_QUEUE_URL
          value: "https://sqs.{{ .Values.aws.region }}.amazonaws.com/{{ .Values.aws.accountId }}/{{ .Values.sqs.notificationQueue.name }}"
        
        # SNS Topics
        - name: ORDER_NOTIFICATIONS_TOPIC_ARN
          value: "arn:aws:sns:{{ .Values.aws.region }}:{{ .Values.aws.accountId }}:{{ .Values.sns.orderNotifications.name }}"
        
        # Application Configuration
        {{- if .Values.debug.enabled }}
        - name: DEBUG
          value: "true"
        - name: LOG_LEVEL
          value: "{{ .Values.debug.logLevel }}"
        {{- end }}
        
        resources:
          requests:
            memory: {{ .Values.inventoryService.resources.requests.memory }}
            cpu: {{ .Values.inventoryService.resources.requests.cpu }}
          limits:
            memory: {{ .Values.inventoryService.resources.limits.memory }}
            cpu: {{ .Values.inventoryService.resources.limits.cpu }}
        
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.inventoryService.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
        
        readinessProbe:
          httpGet:
            path: /ready
            port: {{ .Values.inventoryService.port }}
          initialDelaySeconds: 5
          periodSeconds: 5