# templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: order-processor
  labels:
    app: order-processor
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
type: Opaque
data:
  # Note: This will be created by the deployment script
  # The actual password will be set during deployment
  password: ""