# templates/serviceaccount.yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-api-sa
  namespace: order-processor
  labels:
    app: order-api
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::{{ .Values.aws.accountId }}:role/OrderApiRole"
automountServiceAccountToken: true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-service-sa
  namespace: order-processor
  labels:
    app: inventory-service
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::{{ .Values.aws.accountId }}:role/InventoryServiceRole"
automountServiceAccountToken: true