# File: config/shared-config.yaml
# Simple configuration for cloud-native order processor personal project
# Only contains what's actually used in deployments

project:
  name: "cloud-native-order-processor"
  version: "1.0.0"
  description: "Microservices-based cryptocurrency trading platform"

# AWS Configuration
aws:
  primary_region: "us-west-2"

  # Actually used AWS services
  services:
    - eks          # Kubernetes cluster
    - dynamodb     # Database
    - vpc          # Networking
    - cloudwatch   # Logging
    - iam          # Service account roles

# Infrastructure
infrastructure:
  # Container Orchestration
  kubernetes:
    version: "1.28"
    platform: "eks"

# Application Services (Actually Implemented)
services:
  microservices:
    - name: "auth-service"
      port: 8003
      health_endpoint: "/health"

    - name: "user-service"
      port: 8000
      health_endpoint: "/health"

    - name: "order-service"
      port: 8002
      health_endpoint: "/health"

    - name: "inventory-service"
      port: 8001
      health_endpoint: "/health"

    - name: "gateway"
      port: 8080
      health_endpoint: "/health"

    - name: "frontend"
      port: 3000

# Environments
environments:
  dev:
    description: "Development environment"
    auto_scaling: false
    high_availability: false
    cost_optimization: true

# Monitoring
monitoring:
  logging:
    level: "INFO"
    format: "json"

  metrics:
    enabled: true
    namespace: "OrderProcessor"
