---
# AWS Secrets Store CSI Driver SecretProviderClass
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: order-processor-secrets
  namespace: order-processor
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: ""
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "db-username"
          - path: "password"
            objectAlias: "db-password"
          - path: "host"
            objectAlias: "db-host"
          - path: "port"
            objectAlias: "db-port"
          - path: "dbname"
            objectAlias: "db-name"
  secretObjects:
  - secretName: db-credentials
    type: Opaque
    data:
    - objectName: "db-username"
      key: "username"
    - objectName: "db-password"
      key: "password"
    - objectName: "db-host"
      key: "host"
    - objectName: "db-port"
      key: "port"
    - objectName: "db-name"
      key: "dbname"

---
# ConfigMap for application configuration (Generated from YOUR Terraform outputs)
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: order-processor
  annotations:
    generated-from: terraform-outputs
    generated-at: "2025-06-10T18:29:10Z"
data:
  # Application settings
  APP_NAME: "order-processor-api"
  APP_ENV: "development"
  DEBUG: "true"
  LOG_LEVEL: "INFO"

  # AWS Configuration
  AWS_REGION: "us-west-2"
  AWS_DEFAULT_REGION: "us-west-2"
  AWS_ACCOUNT_ID: "940482447349"

  # EKS Cluster info
  EKS_CLUSTER_NAME: ""
  EKS_CLUSTER_ENDPOINT: ""

  # SNS Topics (from your Terraform outputs)
  SNS_TOPIC_ORDER_EVENTS: ""

  # SQS Queues (from your Terraform outputs)
  SQS_QUEUE_ORDER_PROCESSING: ""

  # S3 Buckets (from your Terraform outputs)
  S3_EVENTS_BUCKET: ""

  # Database Configuration (from your Terraform outputs)
  DATABASE_ENDPOINT: ""

  # ECR Repository
  ECR_REPOSITORY_URL: ""

  # API Configuration
  API_HOST: "0.0.0.0"
  API_PORT: "8000"

  # Feature Flags
  ENABLE_METRICS: "true"
  ENABLE_AUDIT_LOGGING: "true"
  ENABLE_RATE_LIMITING: "false"

# Secret for sensitive configuration
apiVersion: v1
kind: Secret
metadata:
  name: order-service-secrets
  namespace: order-processor
  annotations:
    generated-from: terraform-outputs
    generated-at: "2025-06-10T18:29:10Z"
type: Opaque
stringData:
  DATABASE_SECRET_ARN: ""
  DATABASE_SECRET_NAME: ""
