---
# AWS Secrets Store CSI Driver SecretProviderClass
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: order-processor-secrets
  namespace: order-processor
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "order-processor-dev-db-credentials"
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "db-username"
          - path: "password"
            objectAlias: "db-password"
          - path: "host"
            objectAlias: "db-host"
          - path: "port"
            objectAlias: "db-port"
          - path: "dbname"
            objectAlias: "db-name"
  secretObjects:
  - secretName: db-credentials
    type: Opaque
    data:
    - objectName: "db-username"
      key: "username"
    - objectName: "db-password"
      key: "password"
    - objectName: "db-host"
      key: "host"
    - objectName: "db-port"
      key: "port"
    - objectName: "db-name"
      key: "dbname"

---
# ConfigMap for application configuration (Generated from YOUR Terraform outputs)
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: order-processor
  annotations:
    generated-from: terraform-outputs
    generated-at: "2025-06-09T21:21:52Z"
data:
  # Application settings
  APP_NAME: "order-processor-api"
  APP_ENV: "development"
  DEBUG: "true"
  LOG_LEVEL: "INFO"

  # AWS Configuration
  AWS_REGION: "us-west-2"
  AWS_DEFAULT_REGION: "us-west-2"
  AWS_ACCOUNT_ID: "940482447349"

  # EKS Cluster info
  EKS_CLUSTER_NAME: "order-processor-dev-cluster"
  EKS_CLUSTER_ENDPOINT: "https://F9C1B603DFB7D001BED0F3A51362E523.gr7.us-west-2.eks.amazonaws.com"

  # SNS Topics (from your Terraform outputs)
  SNS_TOPIC_ORDER_EVENTS: "arn:aws:sns:us-west-2:940482447349:order-processor-dev-order-events"

  # SQS Queues (from your Terraform outputs)
  SQS_QUEUE_ORDER_PROCESSING: "https://sqs.us-west-2.amazonaws.com/940482447349/order-processor-dev-order-processing"

  # S3 Buckets (from your Terraform outputs)
  S3_EVENTS_BUCKET: "order-processor-dev-events-hspuicac"

  # Database Configuration (from your Terraform outputs)
  DATABASE_ENDPOINT: "order-processor-dev-postgres.c14o880imgxe.us-west-2.rds.amazonaws.com:5432"
  DATABASE_SECRET_ARN: "arn:aws:secretsmanager:us-west-2:940482447349:secret:order-processor-dev-db-credentials-KjrMIf"
  DATABASE_SECRET_NAME: "order-processor-dev-db-credentials"

  # ECR Repository
  ECR_REPOSITORY_URL: "940482447349.dkr.ecr.us-west-2.amazonaws.com/order-processor-order-api"

  # API Configuration
  API_HOST: "0.0.0.0"
  API_PORT: "8000"

  # Feature Flags
  ENABLE_METRICS: "true"
  ENABLE_AUDIT_LOGGING: "true"
  ENABLE_RATE_LIMITING: "false"
