---
# AWS Secrets Store CSI Driver SecretProviderClass
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: order-processor-secrets
  namespace: order-processor
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "order-processor-dev-db-credentials"
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "db-username"
          - path: "password"
            objectAlias: "db-password"
          - path: "host"
            objectAlias: "db-host"
          - path: "port"
            objectAlias: "db-port"
          - path: "dbname"
            objectAlias: "db-name"
  secretObjects:
  - secretName: db-credentials
    type: Opaque
    data:
    - objectName: "db-username"
      key: "username"
    - objectName: "db-password"
      key: "password"
    - objectName: "db-host"
      key: "host"
    - objectName: "db-port"
      key: "port"
    - objectName: "db-name"
      key: "dbname"

---
# ConfigMap for application configuration (Generated from Terraform)
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: order-processor
  annotations:
    generated-from: terraform-outputs
    generated-at: "2025-07-14T21:30:56Z"
data:
  # Application settings
  APP_NAME: "order-processor-api"
  APP_ENV: "development"
  DEBUG: "true"
  LOG_LEVEL: "INFO"

  # AWS Configuration
  AWS_REGION: "us-west-2"
  AWS_DEFAULT_REGION: "us-west-2"
  AWS_ACCOUNT_ID: "940482447349"

  # SNS Topics (from Terraform outputs)
  SNS_TOPIC_ORDER_EVENTS: ""
  SNS_TOPIC_PAYMENT_EVENTS: ""
  SNS_TOPIC_INVENTORY_EVENTS: ""
  SNS_TOPIC_NOTIFICATION_EVENTS: ""

  # SQS Queues (from Terraform outputs)
  SQS_QUEUE_ORDER_PROCESSING: ""
  SQS_QUEUE_PAYMENT_PROCESSING: ""
  SQS_QUEUE_INVENTORY_PROCESSING: ""
  SQS_QUEUE_NOTIFICATION_PROCESSING: ""

  # S3 Buckets (from Terraform outputs)
  S3_EVENTS_BUCKET: ""
  S3_BACKUP_BUCKET: ""

  # Database Configuration (from Terraform outputs)
  DB_ENDPOINT: ""
  DB_PORT: "5432"

  # API Configuration
  API_HOST: "0.0.0.0"
  API_PORT: "8000"

  # Feature Flags
  ENABLE_METRICS: "true"
  ENABLE_AUDIT_LOGGING: "true"
  ENABLE_RATE_LIMITING: "false"
