---
# Service Account for order-service with IAM role annotation
apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-service-sa
  namespace: order-processor
  annotations:
    # This should match your IAM role ARN created by Terraform
    eks.amazonaws.com/role-arn: arn:aws:iam::940482447349:role/order-processor-dev-pod-role

---
# ClusterRole for secrets access
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
- apiGroups: ["secrets-store.csi.x-k8s.io"]
  resources: ["secretproviderclasses"]
  verbs: ["get", "list"]

---
# ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: order-service-secret-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-reader
subjects:
- kind: ServiceAccount
  name: order-service-sa
  namespace: order-processor