"""
Integration Test Constants
Defines field names and expected values for API response validation
"""

class InventoryFields:
    """Inventory Service API Field Names"""
    ASSET_ID = "asset_id"
    NAME = "name"
    DESCRIPTION = "description"
    CATEGORY = "category"
    PRICE_USD = "price_usd"
    IS_ACTIVE = "is_active"
    AVAILABILITY_STATUS = "availability_status"
    ASSETS = "assets"
    TOTAL_COUNT = "total_count"
    ACTIVE_COUNT = "active_count"
    FILTERS = "filters"

class OrderFields:
    """Order Service API Field Names"""
    ORDER_ID = "order_id"
    USER_ID = "user_id"
    ASSET_ID = "asset_id"
    QUANTITY = "quantity"
    PRICE = "price"
    ORDER_TYPE = "order_type"
    STATUS = "status"
    CREATED_AT = "created_at"
    UPDATED_AT = "updated_at"
    TOTAL_AMOUNT = "total_amount"
    AMOUNT = "amount"
    TRANSACTION_ID = "transaction_id"
    TRANSACTION_TYPE = "transaction_type"
    TIMESTAMP = "timestamp"
    CURRENT_VALUE = "current_value"
    LAST_UPDATED = "last_updated"
    ASSET_BALANCE = "asset_balance"
    TRANSACTIONS = "transactions"
    # Query parameters
    LIMIT = "limit"
    OFFSET = "offset"
    PAGE = "page"
    START_DATE = "start_date"
    END_DATE = "end_date"
    INCLUDE_ZERO = "include_zero"
    CURRENCY = "currency"
    FORMAT = "format"
    INCLUDE_INACTIVE = "include_inactive"
    DETAILED = "detailed"
    INCLUDE_METRICS = "include_metrics"

class UserFields:
    """User Service API Field Names"""
    USER_ID = "user_id"
    USERNAME = "username"
    EMAIL = "email"
    BALANCE = "balance"
    CURRENT_BALANCE = "current_balance"
    CURRENCY = "currency"
    CREATED_AT = "created_at"
    UPDATED_AT = "updated_at"
    FIRST_NAME = "first_name"
    LAST_NAME = "last_name"
    PASSWORD = "password"
    ACCESS_TOKEN = "access_token"
    REFRESH_TOKEN = "refresh_token"
    TOKEN_TYPE = "token_type"
    EXPIRES_IN = "expires_in"
    SUCCESS = "success"
    MESSAGE = "message"
    DATA = "data"
    PHONE = "phone"
    DATE_OF_BIRTH = "date_of_birth"
    MARKETING_EMAILS_CONSENT = "marketing_emails_consent"
    AMOUNT = "amount"
    TRANSACTION_TYPE = "transaction_type"
    TRANSACTIONS = "transactions"

class CommonFields:
    """Common API Field Names"""
    ERROR = "error"
    MESSAGE = "message"
    CODE = "code"
    TIMESTAMP = "timestamp"
    STATUS = "status"
    SERVICE = "service"
    DATA = "data"
    VERSION = "version"
    TOTAL_COUNT = "total_count"
    ORDERS = "orders"
    BALANCES = "balances"
    SORT = "sort"
    PENDING = "pending"
    BUY = "buy"
    SELL = "sell"
    USD = "USD"
    JSON = "json"
    TRUE = "true"
    FALSE = "false"
    # Common query parameters
    LIMIT = "limit"
    OFFSET = "offset"
    PAGE = "page"

class TestValues:
    """Common Test Values"""
    BTC_ASSET_ID = "BTC"
    ETH_ASSET_ID = "ETH"
    TEST_USER_ID = "test_user_123"
    TEST_ORDER_ID = "test_order_123"
    TEST_USERNAME = "testuser"
    TEST_PASSWORD = "testpass"
