name: Test Environment Approval

on:
  push:
    branches: [ main ]

jobs:
  test-job:
    name: Test Job (should pass)
    runs-on: ubuntu-latest
    steps:
      - name: Simple test
        run: echo "✅ This should pass automatically"

  approval-test:
    name: Approval Test (should require approval)
    needs: test-job
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: This should require approval
        run: |
          echo "🎉 If you see this, the approval worked!"
          echo "Environment: production"
          echo "User: ${{ github.actor }}"
          echo "Commit: ${{ github.sha }}"