# values.yaml - Default values that can be overridden
aws:
  region: "us-west-2"
  accountId: ""  # Will be populated from environment
  
# ECR Images
images:
  orderApi:
    repository: ""  # Will be constructed from accountId
    tag: "latest"
  inventoryService:
    repository: ""  # Will be constructed from accountId  
    tag: "latest"
  frontend:
    repository: ""  # Will be constructed from accountId
    tag: "latest"

# Database Configuration
database:
  host: ""  # RDS endpoint from Terraform
  port: 5432
  name: "order_processor"
  username: "admin"
  # Password should come from secret

# SQS Queues (from Terraform outputs)
sqs:
  paymentQueue:
    url: ""  # Will be constructed from accountId and region
    name: "cloud-native-order-processor-payment-processing"
  notificationQueue:
    url: ""  # Will be constructed from accountId and region
    name: "cloud-native-order-processor-notifications"

# SNS Topics (from Terraform outputs)
sns:
  orderNotifications:
    arn: ""  # Will be constructed from accountId and region
    name: "cloud-native-order-processor-order-notifications"

# DynamoDB Tables (from Terraform outputs)
dynamodb:
  ordersTable: "cloud-native-order-processor-orders"
  inventoryTable: "cloud-native-order-processor-inventory"
  usersTable: "cloud-native-order-processor-users"

# Lambda Functions (from Terraform outputs)
lambda:
  paymentProcessor:
    arn: ""  # Will be constructed from accountId and region
    name: "cloud-native-order-processor-payment-processor"
  notificationService:
    arn: ""  # Will be constructed from accountId and region
    name: "cloud-native-order-processor-notification-service"

# VPC Configuration (from Terraform outputs)
vpc:
  id: ""  # VPC ID from Terraform
  subnets:
    private: []  # Private subnet IDs from Terraform
    public: []   # Public subnet IDs from Terraform

# Application Configuration
orderApi:
  replicas: 3
  port: 5000
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "400m"

inventoryService:
  replicas: 2
  port: 8080
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

frontend:
  replicas: 2
  port: 3000
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"